//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 04:00:03 PM CEST 
//


package org.bechclipse.review.model.checklist;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bechclipse.review.model.checklist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Checklist_QNAME = new QName("http://review.bechclipse.org", "checklist");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bechclipse.review.model.checklist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Checkpoint }
     * 
     */
    public Checkpoint createCheckpoint() {
        return new Checkpoint();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link Checklist }
     * 
     */
    public Checklist createChecklist() {
        return new Checklist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checklist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://review.bechclipse.org", name = "checklist")
    public JAXBElement<Checklist> createChecklist(Checklist value) {
        return new JAXBElement<Checklist>(_Checklist_QNAME, Checklist.class, null, value);
    }

}
