//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.02 at 04:00:03 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://review.bechclipse.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.bechclipse.review.model.checklist;
